// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_de51d4WUhqCxGTFKTgpc5EkDuNnmYe8',
    appId: '1:377008952869:web:85c9d18b5657654477d1cc',
    messagingSenderId: '377008952869',
    projectId: 'flutterfire-ui-codelab-8377f',
    authDomain: 'flutterfire-ui-codelab-8377f.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-8377f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ9T1jiTZhvw31_DXtY2HPY9jHNsv3I1Y',
    appId: '1:377008952869:android:b2455408b1e3cbaf77d1cc',
    messagingSenderId: '377008952869',
    projectId: 'flutterfire-ui-codelab-8377f',
    storageBucket: 'flutterfire-ui-codelab-8377f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXpkFUVUj7XJahcsnMYpxppMjcukfyhI',
    appId: '1:377008952869:ios:37308436ec6639d177d1cc',
    messagingSenderId: '377008952869',
    projectId: 'flutterfire-ui-codelab-8377f',
    storageBucket: 'flutterfire-ui-codelab-8377f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXpkFUVUj7XJahcsnMYpxppMjcukfyhI',
    appId: '1:377008952869:ios:37308436ec6639d177d1cc',
    messagingSenderId: '377008952869',
    projectId: 'flutterfire-ui-codelab-8377f',
    storageBucket: 'flutterfire-ui-codelab-8377f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );
}
